name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        node-version: [14.x]
        redis: [5.x]
    name: CI - redis ${{ matrix.redis }}, node ${{ matrix.node-version }}
    steps:
    - name: setup redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: ${{ matrix.redis }}
    - name: ping redis
      run: redis-cli ping
    - uses: actions/checkout@v2
    - name: set node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 3
        command: yarn install
    - name: yarn test
      run: yarn test

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.repository == 'openupm/openupm'
    steps:
    - uses: actions/checkout@v1
    - name: release
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
        branch: master
        semantic_version: 19
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Update the openupm data directory on upm-api
  deploy-upm-api:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.repository == 'openupm/openupm'
    strategy:
      matrix:
        target_host: [HOST_UPM_API]
    steps:
    - name: deploy
      uses: JimCronqvist/action-ssh@master
      with:
        privateKey: ${{ secrets.PRIVATE_KEY }}
        hosts: ${{ secrets.USER }}@${{ secrets[matrix.target_host] }}
        command: |
            cd /home/openupm/openupm
            git pull -q

  deploy-upm-build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.repository == 'openupm/openupm'
    steps:
    - name: deploy
      uses: JimCronqvist/action-ssh@master
      with:
        privateKey: ${{ secrets.PRIVATE_KEY }}
        hosts: ${{ secrets.USER }}@${{ secrets.HOST_UPM_BUILD }}
        command: |
            cd /home/openupm/openupm
            git checkout -- yarn.lock
            git pull -q
            yarn
            export NODE_ENV=production
            git log -m --name-only -1 --pretty="format:" --first-parent master | grep -sqE '^app|^config' && pm2 reload queue-pkg --update-env && pm2 reload queue-rel --update-env || echo skip pm2 queue-pkg/queue-rel reload
            git log -m --name-only -1 --pretty="format:" --first-parent master | grep -sqE '^app|^config|^data' && pm2 reload add-build-package-job --update-env || echo skip pm2 add-build-package-job reload
            git log -m --name-only -1 --pretty="format:" --first-parent master | grep -sqE '^data' && pm2 reload fetch-package-extra --update-env || echo skip pm2 fetch-package-extra reload

  build-website:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.repository == 'openupm/openupm'
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: openupm
          repo: openupm-next
          github_token: ${{ secrets.WORKFLOW_DISPATCH_ACCESS_TOKEN }}
          workflow_file_name: ci.yml
          ref: main
          wait_workflow: false
